spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 123456
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    druid:
      aop-patterns: com.blog.*
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-password: admin
        login-username: admin
        reset-enable: false


      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
logging:
  level:
    org.springframework.web: debug
  file:
    name: myblog.log
